version: '3'

services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    container_name: minio_yt_api
    hostname: minio.host
    ports:
      - 9000:9000
      - 9001:9001
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"  
    restart: always
    env_file: .env
    volumes:
      - ${PWD}/include/minio:/data
    networks:
      - youtube-api_ee6a7e_airflow

networks:
  youtube-api_ee6a7e_airflow:
    external: true
    driver: bridge